apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: terminally-ill-leesah-quiz
  namespace: leesah-quiz
  labels:
    team: leesah-quiz
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    initialdelay: 30
    path: isready
  replicas:
    max: 1
    min: 1
  kafka:
    pool: nav-dev
  prometheus:
    enabled: true
    path: /metrics
  env:
    - name: QUIZ_TOPIC
      value: "leesah-quiz.leesah-rapid-v2"